spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate    # 이미 만들어진 테이블을 다시 drop and create 안하기 위해 사용
    properties:
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: true      # 쿼리 로그 포맷 (정렬)
      show_sql: true        # 쿼리 로그 출력

  h2:
    console:
      enabled: true

