CREATE TABLE product (
    id bigint generated by default as identity,
    brand varchar(255) not null,
    category varchar(255) not null,
    price numeric(38,2) not null,
    primary key (id)
);

CREATE TABLE min_product (
    id bigint generated by default as identity,
    brand varchar(255) not null,
    category varchar(255) not null,
    price numeric(38,2) not null,
    primary key (id)
);

create INDEX idx_min_brand on min_product(brand);

create INDEX idx_brand on product(brand);
create INDEX idx_category on product(category);
create INDEX idx_price on product(price);

CREATE TABLE brand (
    id bigint generated by default as identity,
    brand varchar(255) unique,
    primary key (id)
);